# Generated by Django 5.2.7 on 2025-10-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("merchants", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalreceipt",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="orders.order",
                verbose_name="Related Order",
            ),
        ),
        migrations.AddField(
            model_name="digitalreceipt",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts_issued",
                to="merchants.shop",
                verbose_name="Shop",
            ),
        ),
        migrations.AddField(
            model_name="favoriteshop",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_shops",
                to="customers.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="favoriteshop",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="merchants.shop",
                verbose_name="Shop",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytoken",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_transactions",
                to="customers.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytoken",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="token_transactions",
                to="orders.order",
                verbose_name="Related Order",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalreceipt",
            index=models.Index(
                fields=["customer", "-purchase_date"],
                name="customers_d_custome_397453_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalreceipt",
            index=models.Index(
                fields=["receipt_number"], name="customers_d_receipt_00f635_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalreceipt",
            index=models.Index(
                fields=["expense_type", "is_archived"],
                name="customers_d_expense_bf8bec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="favoriteshop",
            index=models.Index(
                fields=["customer", "created_at"], name="customers_f_custome_39324f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoriteshop",
            unique_together={("customer", "shop")},
        ),
        migrations.AddIndex(
            model_name="loyaltytoken",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="customers_l_custome_34204d_idx",
            ),
        ),
    ]
