# Generated by Django 5.2.7 on 2025-10-11 21:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Official business name",
                        max_length=255,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        help_text="Steuernummer or USt-IdNr.",
                        max_length=50,
                        unique=True,
                        verbose_name="Tax ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "street_address",
                    models.CharField(max_length=255, verbose_name="Street Address"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal Code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="DE", max_length=2, verbose_name="Country Code"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "datev_client_id",
                    models.CharField(
                        blank=True,
                        help_text="For accounting integration",
                        max_length=100,
                        verbose_name="DATEV Client ID",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has completed business verification",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Profile",
                "verbose_name_plural": "Merchant Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Tier (7.3% commission)"),
                            ("premium", "Premium Tier (3.1% commission)"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Subscription Tier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "premium_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Premium Started At"
                    ),
                ),
                (
                    "premium_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Premium Expires At"
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Payment Date"
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Billing Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="merchants.merchantprofile",
                        verbose_name="Merchant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for customers",
                        max_length=255,
                        verbose_name="Shop Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in shop URL",
                        max_length=255,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Tell customers about your shop",
                        verbose_name="Description",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shops/banners/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Contact Phone"),
                ),
                (
                    "delivery_radius_km",
                    models.PositiveIntegerField(
                        default=150,
                        help_text="Maximum distance for deliveries",
                        validators=[django.core.validators.MaxValueValidator(500)],
                        verbose_name="Delivery Radius (km)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Shop is visible to customers",
                        verbose_name="Active",
                    ),
                ),
                (
                    "accepts_online_orders",
                    models.BooleanField(
                        default=True, verbose_name="Accepts Online Orders"
                    ),
                ),
                (
                    "accepts_in_store_pickup",
                    models.BooleanField(
                        default=True, verbose_name="Accepts In-Store Pickup"
                    ),
                ),
                (
                    "total_products",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Products"
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="Total Orders"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="merchants.merchantprofile",
                        verbose_name="Merchant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="merchants_s_slug_66b817_idx"),
                    models.Index(
                        fields=["merchant", "is_active"],
                        name="merchants_s_merchan_1d4f55_idx",
                    ),
                ],
            },
        ),
    ]
